Bugfix/less parallelism
space307/go-utils pull request #33
Opened 2019-01-10 16:15 UTC by s0rg

2019-01-29 20:34 UTC, akolomietc reviewed
Update changelog, please.

2019-02-07 11:40 UTC, andboson requested changes

2019-02-07 11:40 UTC, andboson commented on amqp-kit/api.go
> +						d.Nack(false, false)
Ну тут точно нужно сообщение в лог о том, что ключ не найден, иначе отладка превратится в ад.

2019-02-11 15:39 UTC, s0rg commented on amqp-kit/api.go
> +						d.Nack(false, false)
Nope, if someone use this lib and makes mistake in queue name / key, this situation must be covered by tests. No need to log this garbage.

2019-03-05 13:16 UTC, closed without merging

2019-03-05 13:16 UTC, pilotuser commented
deprecated